### ISSUE TITLE
Why not release Windows version？

### ISSUE THREAD

**Issue by JackrayWang** [apache/pulsar-client-python#61]
Why not release Windows version？

**Comment by BewareMyPower** [comment]
It's a history reason because the 3rd party dependencies are hard to package. I'm going to release the Python client 3.0.0 this week, which should include the wheels for Windows. You can try the previewed version wheels here: https://github.com/BewareMyPower/pulsar-client-python/actions/runs/3570571100

**Comment by BewareMyPower** [comment]
Now you can install the Windows client by `py -m pip install pulsar-client==3.0.0'.
